remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

title: Dong Kyu Shin
description: |
  Undergraduate Researcher

  Seoul National University
  
  B.S. in Mechanical Engineering
  
  B.S. in Artificial Intelligence

logo: /assets/profile.png

# Contact information
email: dkshin99@snu.ac.kr

# Social links
github_username: DonkeyU99
linkedin_username: dkshin99

# Show/hide elements
show_downloads: false

# Theme customization
markdown: kramdown
